version: "3"
services:
  web:
    build: .
    ports:
      - 8080:8080
    # DB接続情報にはこちらが使用される
    environment:
      MYSQL_DATABASE: todo
      # MYSQL_HOSTにDBコンテナ名を指定
      MYSQL_HOST: todo_gin-db-1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - .:/go/src/todo_gin
    tty: true
    stdin_open: true
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    # DBコンテナ名を指定
    container_name: todo_gin-db-1
    # M1のCPUは、linux/arm64/v8を使用しているため、M1の場合はプラットフォームを指定
    platform: linux/x86_64
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: todo 
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # DBを日本語設定にする
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
